site_name: NEONPAY API
site_url: https://neongaddar.github.io/docs/
theme:
  name: material
  language: ru
  features:
    - navigation.top
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.copy

nav:
  - Главная: index.md
  - Руководство: guide.md
  - API: api.md
